homepage: https://github.com/patrickt/fused-effects-exceptions#readme
changelog-type: ''
hash: 1dd2acfe9e2bd7d2c0422f1a9368c7be0fc8b59c3f0a5952a54dd273cb20f3d4
test-bench-deps: {}
maintainer: patrickt@github.com
synopsis: Handle exceptions thrown in IO with fused-effects.
changelog: ''
basic-deps:
  base: ! '>=4.7 && <5'
  safe-exceptions: ! '>=0.1 && <1'
  unliftio-core: ! '>=0.1.2 && <1'
  fused-effects: ! '>=0.3 && <1'
all-versions:
- 0.1.0.0
- 0.1.1.0
author: Josh Vera
latest: 0.1.1.0
description-type: markdown
description: |
  # fused-effects-exceptions

  This package provides functionality to handle exceptions thrown in the `IO` monad. It delegates to `catch` from `Control.Exception`. An additional `catchSync` primitive is provided to handle the common case of catching only synchronous exceptions.

  This implementation was extracted from one originally written by Josh Vera. It requires a version of `fused-effects` later than 0.3.
license-name: BSD-3-Clause
