homepage: https://github.com/fused-effects/fused-effects-exceptions#readme
changelog-type: ''
hash: a4925cdf5fd57a7ed5e603e1d8d1de0f227654d0137b9643d0b3807804f2ff08
test-bench-deps: {}
maintainer: patrickt@github.com
synopsis: Handle exceptions thrown in IO with fused-effects.
changelog: ''
basic-deps:
  base: ! '>=4.7 && <5'
  safe-exceptions: ! '>=0.1 && <1'
  unliftio-core: ! '>=0.1.2 && <1'
  fused-effects: ^>=0.5
all-versions:
- 0.1.0.0
- 0.1.1.0
- 0.2.0.0
author: Josh Vera
latest: 0.2.0.0
description-type: markdown
description: |
  # fused-effects-exceptions

  This package provides functionality to handle exceptions thrown in the `IO` monad. It delegates to `catch` from `Control.Exception`. An additional `catchSync` primitive is provided to handle the common case of catching only synchronous exceptions.

  This implementation was extracted from one originally written by Josh Vera. It requires a version of `fused-effects` later than 0.3.
license-name: BSD-3-Clause
